### ISSUE TITLE
Build @carbon/ibm-cloud-paks npm module 

### ISSUE THREAD

**Issue by dbrugger** [carbon-design-system/ibm-cloud-paks#11]

**Comment by SimonFinney** [comment]
Acceptance criteria to be defined in Slack

**Comment by Georgegriff** [comment]
It was discussed on the call with ide-components guild that it might be an idea to have separate releases for patterns

- Given that the patterns themselves are individually versioned and changed.
- This will help us deal with breaking changes.
- We can release patterns into the open source one by one much easier
- We could consider a `core` package which contains some of the smaller more common, or pattern agnostic components. e.g. Buttons,  DataTable

If we ensure that we maintain one shared build pipeline i think the overhead here will be worth it.

**Comment by joker23** [comment]
@joshblack is there an existing build pipeline for carbon that we can leverage here? Some additional considerations (maybe I just need more clarification here):

- I thought I heard that we want to settle on a monthly delivery cadence. If that is true then how do we organize individual versioning?
- Are there any documentations on how we should do dogfooding before releasing?
@SimonFinney

**Comment by SimonFinney** [comment]
@gatfora / @Georgegriff I'd like to understand more about what we mean when we say component and pattern versioning - Are we talking about a component and pattern lifecycle, similar to what IDE does today, or truly individual packages?

**Comment by Georgegriff** [comment]
At this point it was mostly a suggestion but I think we're talking about individually versions npm packages with one or more components in them, the reason being if we/design have to break a single pattern it's easier to deal with

**Comment by joker23** [comment]
would it make sense to align any of the versioning? eg if we aligned the major minor versions for monthly release cadence (which introduces new features, new functions, etc) and have teams increment their patch version as needed?

I guess all of this is mostly semantics since it still relies on a build model and tooling that supports individual team build/publish.

**Comment by joshblack** [comment]
@joker23 definitely can share our setup and plans moving forward. Probably the simplest option for the monorepo here is to use Lerna plus a timed GitHub action if you all want to release on a schedule 👀  

Lerna can help with versioning/publishing based on conventional commits, it can also help with cutting pre-releases for nightly builds or release candidates.

In general, we follow a time-based release schedule matching the following for a given month:

![image](https://user-images.githubusercontent.com/3901764/89679003-d0ae8580-d8b5-11ea-9166-84f061bcec8c.png)

- Nightlies occur daily
- Hotfixes are published as-needed on off weeks as patches
- Minors are published every other week (~26 releases/year)
- Release candidates are published the week of the release and floated to smoke test teams

Looking forward, we're going to start moving towards two types of packages:

- Component-specific packages, contain only the relevant component code and docs
- Entrypoint packages, combine component packages into a single entrypoint

---

Separately, let me know if you all want to collaborate on any of the smoke-testing tooling for having teams try-out pre-releases! Our hope is to automate this process further on our end and use it to drive go/no-go decisions on releases or specific features.
