### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-paks#21]
### Primary

- [ ] Basic Jest and React Testing Library configuration
- [ ] Testing suite should run on each build

#### Documentation

- [ ] Links for guidance on behavioural testing and configuration
- [ ] Test structure
- [ ] Examples

**Comment by SimonFinney** [comment]
Acceptance criteria to be defined in GitHub by owner in collaboration with group

**Comment by davidmenendez** [comment]
PR up here https://github.com/carbon-design-system/ibm-cloud-paks/pull/86 which sets up enzyme to do react testing
