### ISSUE TITLE
Web terminal

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-paks#28]
https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/91

**Comment by carrenelloyd** [comment]
[Link to Design](https://pages.github.ibm.com/cdai-design/pal/patterns/web-terminal/)

Maintainer: Marci Coral

Catalog number: 28

**Comment by SimonFinney** [comment]
Duplicate of #70
