### ISSUE TITLE
Code styling

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-paks#6]
## Summary

Discussion around how code styling could work across Cloud Pak components packages, and what best practices are available to be leveraged from Carbon.

- [ ] Code design and style decisions
- [ ] Linting and rules - `eslint` / `stylelint` configuration
- [ ] Formatting - Tabs versus spaces, Prettier configuration?

**Comment by ericabr** [comment]
Will we be adopting the linter styles from carbon?

**Comment by SimonFinney** [comment]
My personal preference is yes, so we don't have to worry about it, but I'm not strongly bound to that 😄

**Comment by SimonFinney** [comment]
https://github.com/carbon-design-system/carbon/pull/6695

**Comment by davidmenendez** [comment]
Looks like there's been a few PR's dedicated to this issue. Is there anything else that needs to be done to satisfy the requirements for this issue?

**Comment by SimonFinney** [comment]
This LGTM for now!

**Comment by lee-chase** [comment]
Happy for this to be closed pending more specific future needs.
