### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-paks#7]
## Summary

Discussion around how release management could work across Cloud Pak components packages, and what best practices are available to be leveraged from Carbon.

### Questions

Lerna versus `semantic-release`

**Comment by ericabr** [comment]
Lerna is made for our mono repo it seems
I have never heard of lerna before. I'm going to read up on it.

**Comment by SimonFinney** [comment]
Duplicate of #12
